SET FOREIGN_KEY_CHECKS=0;
USE placement_cell;
INSERT IGNORE INTO users (email, password, role) VALUES ('saikumar21020@gmail.com', '459CE20019', 'STUDENT');
SET @uid = (SELECT id FROM users WHERE email = 'saikumar21020@gmail.com');
INSERT IGNORE INTO students (user_id, register_number, full_name, date_of_birth, gender, branch, mobile_number, alternate_number, address, approval_status, placement_status, placed_company) VALUES (@uid, '459CE20019', 'SAI KUMAR', '2003-08-02', 'Male', 'Civil', '9353830798', '8197873959', 'Rupanagudi Road Near Akkasaligar street bellary', 'APPROVED', 'UNPLACED', '');
SET @sid = (SELECT id FROM students WHERE user_id = @uid);
INSERT IGNORE INTO academic_details (student_id, sslc_percentage, sslc_year, puc_percentage, puc_year, iti_percentage, iti_year, sem1, sem2, sem3, sem4, diploma_percentage, current_backlog_count, history_of_backlogs, preference) VALUES (@sid, 67.2, '2020', 0.0, '', 0.0, '', 50.03, 73.04, 40.02, 49.04, 212.13, 2, 'Yes', 'Job');
INSERT IGNORE INTO users (email, password, role) VALUES ('abdulrehman76141@gmail.com', '459CE23002', 'STUDENT');
SET @uid = (SELECT id FROM users WHERE email = 'abdulrehman76141@gmail.com');
INSERT IGNORE INTO students (user_id, register_number, full_name, date_of_birth, gender, branch, mobile_number, alternate_number, address, approval_status, placement_status, placed_company) VALUES (@uid, '459CE23002', 'ABDUL REHMAN', '2003-09-19', 'Male', 'Civil', '9945216039', '8217627806', 'Near society rice mill, millerpet, Ballari', 'APPROVED', 'UNPLACED', '');
SET @sid = (SELECT id FROM students WHERE user_id = @uid);
INSERT IGNORE INTO academic_details (student_id, sslc_percentage, sslc_year, puc_percentage, puc_year, iti_percentage, iti_year, sem1, sem2, sem3, sem4, diploma_percentage, current_backlog_count, history_of_backlogs, preference) VALUES (@sid, 50.56, '2019-2020', 0.0, '', 0.0, '', 84.7, 86.0, 88.0, 87.9, 87.65, 0, 'No', 'Job');
INSERT IGNORE INTO users (email, password, role) VALUES ('shaikafzal01290@gmail.com', '459CE23003', 'STUDENT');
SET @uid = (SELECT id FROM users WHERE email = 'shaikafzal01290@gmail.com');
INSERT IGNORE INTO students (user_id, register_number, full_name, date_of_birth, gender, branch, mobile_number, alternate_number, address, approval_status, placement_status, placed_company) VALUES (@uid, '459CE23003', 'AFZAL S', '2006-09-10', 'Male', 'Civil', '8618490608', '6360798819', 'Cowl bazar sharef street ballari', 'APPROVED', 'UNPLACED', '');
SET @sid = (SELECT id FROM students WHERE user_id = @uid);
INSERT IGNORE INTO academic_details (student_id, sslc_percentage, sslc_year, puc_percentage, puc_year, iti_percentage, iti_year, sem1, sem2, sem3, sem4, diploma_percentage, current_backlog_count, history_of_backlogs, preference) VALUES (@sid, 65.0, '2023', 0.0, '', 0.0, '', 50.3, 24.3, 61.7, 60.2, 49.125, 3, 'Yes', 'Job');
INSERT IGNORE INTO users (email, password, role) VALUES ('akbaralibennur227@gmail.com', '459CE23004', 'STUDENT');
SET @uid = (SELECT id FROM users WHERE email = 'akbaralibennur227@gmail.com');
INSERT IGNORE INTO students (user_id, register_number, full_name, date_of_birth, gender, branch, mobile_number, alternate_number, address, approval_status, placement_status, placed_company) VALUES (@uid, '459CE23004', 'AKBAR', '2005-06-22', 'Male', 'Civil', '9591226837', '6362578810', '2nd Ward Bennuru, PO Oolenur Sub District Gangavathi  PIN Code : 583229', 'APPROVED', 'UNPLACED', '');
SET @sid = (SELECT id FROM students WHERE user_id = @uid);
INSERT IGNORE INTO academic_details (student_id, sslc_percentage, sslc_year, puc_percentage, puc_year, iti_percentage, iti_year, sem1, sem2, sem3, sem4, diploma_percentage, current_backlog_count, history_of_backlogs, preference) VALUES (@sid, 83.2, '2021', 0.0, '', 0.0, '', 73.6, 49.8, 51.7, 56.3, 57.85, 0, 'Yes', 'Job');
INSERT IGNORE INTO users (email, password, role) VALUES ('pprajawal033@gmail.com', '459CE23006', 'STUDENT');
SET @uid = (SELECT id FROM users WHERE email = 'pprajawal033@gmail.com');
INSERT IGNORE INTO students (user_id, register_number, full_name, date_of_birth, gender, branch, mobile_number, alternate_number, address, approval_status, placement_status, placed_company) VALUES (@uid, '459CE23006', 'B M PRAJWAL KUMAR', '2026-01-07', 'Male', 'Civil', '7676391800', '7676391800', 'TALU ROAD Renuka Nagar 1st cross', 'APPROVED', 'UNPLACED', '');
SET @sid = (SELECT id FROM students WHERE user_id = @uid);
INSERT IGNORE INTO academic_details (student_id, sslc_percentage, sslc_year, puc_percentage, puc_year, iti_percentage, iti_year, sem1, sem2, sem3, sem4, diploma_percentage, current_backlog_count, history_of_backlogs, preference) VALUES (@sid, 68.0, '2023', 0.0, '', 0.0, '', 53.6, 33.4, 43.3, 57.1, 46.85, 3, 'Yes', 'Job');
INSERT IGNORE INTO users (email, password, role) VALUES ('revanth4214y.com@gmail.com', '459CE23007', 'STUDENT');
SET @uid = (SELECT id FROM users WHERE email = 'revanth4214y.com@gmail.com');
INSERT IGNORE INTO students (user_id, register_number, full_name, date_of_birth, gender, branch, mobile_number, alternate_number, address, approval_status, placement_status, placed_company) VALUES (@uid, '459CE23007', 'B REVANTH', '2007-01-13', 'Male', 'Civil', '7022960451', '8660198346', 'RENUKA NAGAR 12TH CROSS TALUR ROAD BALLAR', 'APPROVED', 'UNPLACED', '');
SET @sid = (SELECT id FROM students WHERE user_id = @uid);
INSERT IGNORE INTO academic_details (student_id, sslc_percentage, sslc_year, puc_percentage, puc_year, iti_percentage, iti_year, sem1, sem2, sem3, sem4, diploma_percentage, current_backlog_count, history_of_backlogs, preference) VALUES (@sid, 70.56, '2022-23', 0.0, '', 0.0, '', 62.5, 56.1, 59.4, 61.0, 59.75, 0, 'Yes', 'Job');
INSERT IGNORE INTO users (email, password, role) VALUES ('bsanju2112@gamil.com', '459CE23008', 'STUDENT');
SET @uid = (SELECT id FROM users WHERE email = 'bsanju2112@gamil.com');
INSERT IGNORE INTO students (user_id, register_number, full_name, date_of_birth, gender, branch, mobile_number, alternate_number, address, approval_status, placement_status, placed_company) VALUES (@uid, '459CE23008', 'B SANJU', '2007-05-21', 'Female', 'Civil', '7338183668', '9071841955', 'W. No:3, near veerbhadra temple, k belagal', 'APPROVED', 'UNPLACED', '');
SET @sid = (SELECT id FROM students WHERE user_id = @uid);
INSERT IGNORE INTO academic_details (student_id, sslc_percentage, sslc_year, puc_percentage, puc_year, iti_percentage, iti_year, sem1, sem2, sem3, sem4, diploma_percentage, current_backlog_count, history_of_backlogs, preference) VALUES (@sid, 79.6, '2022-2023', 0.0, '', 0.0, '', 88.1, 90.7, 92.5, 92.5, 90.95, 0, 'No', 'Job');
INSERT IGNORE INTO users (email, password, role) VALUES ('ywant4632@gmail.com', '459CE23009', 'STUDENT');
SET @uid = (SELECT id FROM users WHERE email = 'ywant4632@gmail.com');
INSERT IGNORE INTO students (user_id, register_number, full_name, date_of_birth, gender, branch, mobile_number, alternate_number, address, approval_status, placement_status, placed_company) VALUES (@uid, '459CE23009', 'B YASHWANTHA', '2006-10-26', 'Male', 'Civil', '9353151901', '9901555795', 'W .no 35, Siruguppa Road, near canal havambavi, ballari', 'APPROVED', 'UNPLACED', '');
SET @sid = (SELECT id FROM students WHERE user_id = @uid);
INSERT IGNORE INTO academic_details (student_id, sslc_percentage, sslc_year, puc_percentage, puc_year, iti_percentage, iti_year, sem1, sem2, sem3, sem4, diploma_percentage, current_backlog_count, history_of_backlogs, preference) VALUES (@sid, 61.0, '2022', 0.0, '', 0.0, '', 55.8, 25.2, 56.3, 53.3, 47.65, 3, 'Yes', 'Job');
INSERT IGNORE INTO users (email, password, role) VALUES ('bharteeshh@gmail.com', '459CE23011', 'STUDENT');
SET @uid = (SELECT id FROM users WHERE email = 'bharteeshh@gmail.com');
INSERT IGNORE INTO students (user_id, register_number, full_name, date_of_birth, gender, branch, mobile_number, alternate_number, address, approval_status, placement_status, placed_company) VALUES (@uid, '459CE23011', 'BHARATEESH H M', '2008-04-25', 'Male', 'Civil', '6366517837', '9844854533', 'WNO 5.MAIN ROAD,KOLAGALLU POST,BALLARI DIST', 'APPROVED', 'UNPLACED', '');
SET @sid = (SELECT id FROM students WHERE user_id = @uid);
INSERT IGNORE INTO academic_details (student_id, sslc_percentage, sslc_year, puc_percentage, puc_year, iti_percentage, iti_year, sem1, sem2, sem3, sem4, diploma_percentage, current_backlog_count, history_of_backlogs, preference) VALUES (@sid, 81.12, '2023', 0.0, '', 0.0, '', 70.3, 52.5, 62.5, 58.7, 61.0, 0, 'No', 'Higher Education');
INSERT IGNORE INTO users (email, password, role) VALUES ('cbkiran741@gmail.com', '459CE23012', 'STUDENT');
SET @uid = (SELECT id FROM users WHERE email = 'cbkiran741@gmail.com');
INSERT IGNORE INTO students (user_id, register_number, full_name, date_of_birth, gender, branch, mobile_number, alternate_number, address, approval_status, placement_status, placed_company) VALUES (@uid, '459CE23012', 'C KIRAN', '2004-06-24', 'Male', 'Civil', '7204825674', '9743645840', '#4/70 Asraya colony, Ganganagar, Bhuvanahalli 583223', 'APPROVED', 'UNPLACED', '');
SET @sid = (SELECT id FROM students WHERE user_id = @uid);
INSERT IGNORE INTO academic_details (student_id, sslc_percentage, sslc_year, puc_percentage, puc_year, iti_percentage, iti_year, sem1, sem2, sem3, sem4, diploma_percentage, current_backlog_count, history_of_backlogs, preference) VALUES (@sid, 64.96, '2020-21', 0.0, '', 0.0, '', 64.7, 38.9, 68.5, 73.3, 61.35, 2, 'Yes', 'Job');
INSERT IGNORE INTO users (email, password, role) VALUES ('mamathamamatha5521@gmail.com', '459CE23013', 'STUDENT');
SET @uid = (SELECT id FROM users WHERE email = 'mamathamamatha5521@gmail.com');
INSERT IGNORE INTO students (user_id, register_number, full_name, date_of_birth, gender, branch, mobile_number, alternate_number, address, approval_status, placement_status, placed_company) VALUES (@uid, '459CE23013', 'C MAMATHA', '2007-11-23', 'Female', 'Civil', '8867052522', '7899461138', 'Hospet road Rajiv Gandhi Nagar cantonment ballari', 'APPROVED', 'UNPLACED', '');
SET @sid = (SELECT id FROM students WHERE user_id = @uid);
INSERT IGNORE INTO academic_details (student_id, sslc_percentage, sslc_year, puc_percentage, puc_year, iti_percentage, iti_year, sem1, sem2, sem3, sem4, diploma_percentage, current_backlog_count, history_of_backlogs, preference) VALUES (@sid, 54.4, '2023', 0.0, '', 0.0, '', 73.6, 68.0, 80.2, 82.5, 76.08, 0, 'Yes', 'Higher Education');
INSERT IGNORE INTO users (email, password, role) VALUES ('chaitra9035s@gmail.com', '459CE23014', 'STUDENT');
SET @uid = (SELECT id FROM users WHERE email = 'chaitra9035s@gmail.com');
INSERT IGNORE INTO students (user_id, register_number, full_name, date_of_birth, gender, branch, mobile_number, alternate_number, address, approval_status, placement_status, placed_company) VALUES (@uid, '459CE23014', 'CHAITRA S', '2025-05-16', 'Female', 'Civil', '9035882926', '9035882926', 'House no 10 ward no 11, pattana shetty street near jumma masid Ballari', 'APPROVED', 'UNPLACED', '');
SET @sid = (SELECT id FROM students WHERE user_id = @uid);
INSERT IGNORE INTO academic_details (student_id, sslc_percentage, sslc_year, puc_percentage, puc_year, iti_percentage, iti_year, sem1, sem2, sem3, sem4, diploma_percentage, current_backlog_count, history_of_backlogs, preference) VALUES (@sid, 56.8, '2020', 0.0, '', 0.0, '', 83.6, 78.9, 91.0, 92.5, 86.5, 0, 'No', 'Job');
INSERT IGNORE INTO users (email, password, role) VALUES ('chaturvedi45king@gmail.com', '459CE23015', 'STUDENT');
SET @uid = (SELECT id FROM users WHERE email = 'chaturvedi45king@gmail.com');
INSERT IGNORE INTO students (user_id, register_number, full_name, date_of_birth, gender, branch, mobile_number, alternate_number, address, approval_status, placement_status, placed_company) VALUES (@uid, '459CE23015', 'CHATURVEDI E', '2005-12-11', 'Male', 'Civil', '9111400000', '9198460000', '# 33 ,ward no 29, Kawadi Street ,Kamela Road ,Near Anjiniya Temple ,Cowl Bazar Ballari 583101', 'APPROVED', 'UNPLACED', '');
SET @sid = (SELECT id FROM students WHERE user_id = @uid);
INSERT IGNORE INTO academic_details (student_id, sslc_percentage, sslc_year, puc_percentage, puc_year, iti_percentage, iti_year, sem1, sem2, sem3, sem4, diploma_percentage, current_backlog_count, history_of_backlogs, preference) VALUES (@sid, 45.92, 'June 2023-24', 0.0, '', 0.0, '', 40.3, 24.3, 46.3, 53.3, 41.05, 3, 'Yes', 'Job');
INSERT IGNORE INTO users (email, password, role) VALUES ('earshancd381@gmail.com', '459CE23016', 'STUDENT');
SET @uid = (SELECT id FROM users WHERE email = 'earshancd381@gmail.com');
INSERT IGNORE INTO students (user_id, register_number, full_name, date_of_birth, gender, branch, mobile_number, alternate_number, address, approval_status, placement_status, placed_company) VALUES (@uid, '459CE23016', 'DARSHAN', '2005-02-11', 'Male', 'Civil', '7353566901', '7892917722', 'Kudethine', 'APPROVED', 'UNPLACED', '');
SET @sid = (SELECT id FROM students WHERE user_id = @uid);
INSERT IGNORE INTO academic_details (student_id, sslc_percentage, sslc_year, puc_percentage, puc_year, iti_percentage, iti_year, sem1, sem2, sem3, sem4, diploma_percentage, current_backlog_count, history_of_backlogs, preference) VALUES (@sid, 374.0, '2023', 0.0, '', 0.0, '', 66.9, 55.2, 67.1, 68.7, 64.47, 0, 'Yes', 'Job');
INSERT IGNORE INTO users (email, password, role) VALUES ('vd3786715@gmail.com', '459CE23018', 'STUDENT');
SET @uid = (SELECT id FROM users WHERE email = 'vd3786715@gmail.com');
INSERT IGNORE INTO students (user_id, register_number, full_name, date_of_birth, gender, branch, mobile_number, alternate_number, address, approval_status, placement_status, placed_company) VALUES (@uid, '459CE23018', 'DURGA PRASAD', '2006-03-12', 'Male', 'Civil', '9591649488', '6362936126', 'KC road near Raghavendra theatre ballari', 'APPROVED', 'UNPLACED', '');
SET @sid = (SELECT id FROM students WHERE user_id = @uid);
INSERT IGNORE INTO academic_details (student_id, sslc_percentage, sslc_year, puc_percentage, puc_year, iti_percentage, iti_year, sem1, sem2, sem3, sem4, diploma_percentage, current_backlog_count, history_of_backlogs, preference) VALUES (@sid, 56.0, '2023', 0.0, '', 0.0, '', 76.0, 58.0, 79.4, 82.5, 74.2, 0, 'No', 'Higher Education');
INSERT IGNORE INTO users (email, password, role) VALUES ('H.Malathi2007@gmail.com', '459CE23019', 'STUDENT');
SET @uid = (SELECT id FROM users WHERE email = 'H.Malathi2007@gmail.com');
INSERT IGNORE INTO students (user_id, register_number, full_name, date_of_birth, gender, branch, mobile_number, alternate_number, address, approval_status, placement_status, placed_company) VALUES (@uid, '459CE23019', 'H MALATHI', '2007-01-10', 'Female', 'Civil', '9980848030', '9980848030', 'W.NO.10 NEAR BIG MARKET SALESHWARA TEMPLE BELLARY', 'APPROVED', 'UNPLACED', '');
SET @sid = (SELECT id FROM students WHERE user_id = @uid);
INSERT IGNORE INTO academic_details (student_id, sslc_percentage, sslc_year, puc_percentage, puc_year, iti_percentage, iti_year, sem1, sem2, sem3, sem4, diploma_percentage, current_backlog_count, history_of_backlogs, preference) VALUES (@sid, 56.0, '2023', 0.0, '', 0.0, '', 79.6, 66.1, 86.3, 87.9, 79.87, 0, 'Yes', 'Job');
INSERT IGNORE INTO users (email, password, role) VALUES ('manjumanjuu690@gmail.com', '459CE23021', 'STUDENT');
SET @uid = (SELECT id FROM users WHERE email = 'manjumanjuu690@gmail.com');
INSERT IGNORE INTO students (user_id, register_number, full_name, date_of_birth, gender, branch, mobile_number, alternate_number, address, approval_status, placement_status, placed_company) VALUES (@uid, '459CE23021', 'K MANJUNATH', '2007-06-01', 'Male', 'Civil', '7675316399', '9741719669', 'Thayamma temple , CHITIGINAHALU, ballari', 'APPROVED', 'UNPLACED', '');
SET @sid = (SELECT id FROM students WHERE user_id = @uid);
INSERT IGNORE INTO academic_details (student_id, sslc_percentage, sslc_year, puc_percentage, puc_year, iti_percentage, iti_year, sem1, sem2, sem3, sem4, diploma_percentage, current_backlog_count, history_of_backlogs, preference) VALUES (@sid, 47976.64, '2023', 0.0, '', 0.0, '', 65.8, 56.1, 67.1, 66.3, 63.75, 0, 'Yes', 'Higher Education');
INSERT IGNORE INTO users (email, password, role) VALUES ('Vijaykumar7674vk@gmail.com', '459CE23023', 'STUDENT');
SET @uid = (SELECT id FROM users WHERE email = 'Vijaykumar7674vk@gmail.com');
INSERT IGNORE INTO students (user_id, register_number, full_name, date_of_birth, gender, branch, mobile_number, alternate_number, address, approval_status, placement_status, placed_company) VALUES (@uid, '459CE23023', 'K VIJAYAKUMARA', '2006-09-18', 'Male', 'Civil', '6360831744', '6361422700', 'HAGALURU.HOSALLI', 'APPROVED', 'UNPLACED', '');
SET @sid = (SELECT id FROM students WHERE user_id = @uid);
INSERT IGNORE INTO academic_details (student_id, sslc_percentage, sslc_year, puc_percentage, puc_year, iti_percentage, iti_year, sem1, sem2, sem3, sem4, diploma_percentage, current_backlog_count, history_of_backlogs, preference) VALUES (@sid, -55.68, '2022', 0.0, '', 0.0, '', 64.7, 57.0, 63.3, 64.0, 62.25, 0, 'No', 'Job');
INSERT IGNORE INTO users (email, password, role) VALUES ('madhumravi02@gmail.com', '459CE23025', 'STUDENT');
SET @uid = (SELECT id FROM users WHERE email = 'madhumravi02@gmail.com');
INSERT IGNORE INTO students (user_id, register_number, full_name, date_of_birth, gender, branch, mobile_number, alternate_number, address, approval_status, placement_status, placed_company) VALUES (@uid, '459CE23025', 'M MADHU', '2007-12-02', 'Male', 'Civil', '9380004314', '9008566582', 'Siruguppa sada Shiva Nagar', 'APPROVED', 'UNPLACED', '');
SET @sid = (SELECT id FROM students WHERE user_id = @uid);
INSERT IGNORE INTO academic_details (student_id, sslc_percentage, sslc_year, puc_percentage, puc_year, iti_percentage, iti_year, sem1, sem2, sem3, sem4, diploma_percentage, current_backlog_count, history_of_backlogs, preference) VALUES (@sid, 69.6, '2023', 0.0, '', 0.0, '', 88.1, 89.8, 91.7, 92.5, 90.52, 0, 'No', 'Job');
INSERT IGNORE INTO users (email, password, role) VALUES ('mskhader2007@gmail.com', '459CE23026', 'STUDENT');
SET @uid = (SELECT id FROM users WHERE email = 'mskhader2007@gmail.com');
INSERT IGNORE INTO students (user_id, register_number, full_name, date_of_birth, gender, branch, mobile_number, alternate_number, address, approval_status, placement_status, placed_company) VALUES (@uid, '459CE23026', 'M S KHADAR BASHA NIZAMI', '2007-05-01', 'Male', 'Civil', '9008345209', '9008345209', 'Ghughurahatti near hanuman bakery ballari 583101', 'APPROVED', 'UNPLACED', '');
SET @sid = (SELECT id FROM students WHERE user_id = @uid);
INSERT IGNORE INTO academic_details (student_id, sslc_percentage, sslc_year, puc_percentage, puc_year, iti_percentage, iti_year, sem1, sem2, sem3, sem4, diploma_percentage, current_backlog_count, history_of_backlogs, preference) VALUES (@sid, 51.0, '2022', 0.0, '2022, 2023', 0.0, '', 42.5, 23.3, 43.3, 44.0, 38.27, 3, 'Yes', 'Job');
INSERT IGNORE INTO users (email, password, role) VALUES ('manikanta44456@gmail.com', '459CE23028', 'STUDENT');
SET @uid = (SELECT id FROM users WHERE email = 'manikanta44456@gmail.com');
INSERT IGNORE INTO students (user_id, register_number, full_name, date_of_birth, gender, branch, mobile_number, alternate_number, address, approval_status, placement_status, placed_company) VALUES (@uid, '459CE23028', 'MANIKANTA G', '2007-05-10', 'Male', 'Civil', '9686491795', '9945992099', 'Sindigeri', 'APPROVED', 'UNPLACED', '');
SET @sid = (SELECT id FROM students WHERE user_id = @uid);
INSERT IGNORE INTO academic_details (student_id, sslc_percentage, sslc_year, puc_percentage, puc_year, iti_percentage, iti_year, sem1, sem2, sem3, sem4, diploma_percentage, current_backlog_count, history_of_backlogs, preference) VALUES (@sid, 71.0, '2022-2023', 0.0, '', 0.0, '', 69.2, 54.3, 62.5, 56.3, 60.57, 0, 'Yes', 'Higher Education');
INSERT IGNORE INTO users (email, password, role) VALUES ('shehzadaimmu2008@gmail.com', '459CE23030', 'STUDENT');
SET @uid = (SELECT id FROM users WHERE email = 'shehzadaimmu2008@gmail.com');
INSERT IGNORE INTO students (user_id, register_number, full_name, date_of_birth, gender, branch, mobile_number, alternate_number, address, approval_status, placement_status, placed_company) VALUES (@uid, '459CE23030', 'MOHAMMAD IMRAN P', '2008-05-26', 'Male', 'Civil', '9742315306', '9731078994', 'Near new bus stand, near balanjineya temple, bellary', 'APPROVED', 'UNPLACED', '');
SET @sid = (SELECT id FROM students WHERE user_id = @uid);
INSERT IGNORE INTO academic_details (student_id, sslc_percentage, sslc_year, puc_percentage, puc_year, iti_percentage, iti_year, sem1, sem2, sem3, sem4, diploma_percentage, current_backlog_count, history_of_backlogs, preference) VALUES (@sid, 65.0, '2022', 0.0, '', 0.0, '', 68.0, 61.0, 62.0, 62.0, 63.32, 0, 'No', 'Higher Education');
INSERT IGNORE INTO users (email, password, role) VALUES ('Md.ibrahim092006@gmail.com', '459CE23033', 'STUDENT');
SET @uid = (SELECT id FROM users WHERE email = 'Md.ibrahim092006@gmail.com');
INSERT IGNORE INTO students (user_id, register_number, full_name, date_of_birth, gender, branch, mobile_number, alternate_number, address, approval_status, placement_status, placed_company) VALUES (@uid, '459CE23033', 'MOHAMMED IBRAHIM KHAN', '2006-11-09', 'Male', 'Civil', '9972505057', '6360540962', 'Guggarahatti Raja Sahab Colony bellari', 'APPROVED', 'UNPLACED', '');
SET @sid = (SELECT id FROM students WHERE user_id = @uid);
INSERT IGNORE INTO academic_details (student_id, sslc_percentage, sslc_year, puc_percentage, puc_year, iti_percentage, iti_year, sem1, sem2, sem3, sem4, diploma_percentage, current_backlog_count, history_of_backlogs, preference) VALUES (@sid, 55.0, '23', 0.0, '', 0.0, '', 55.8, 49.8, 54.8, 66.3, 56.67, 1, 'Yes', 'Higher Education');
INSERT IGNORE INTO users (email, password, role) VALUES ('shaikimran1027@gmail.com', '459CE23034', 'STUDENT');
SET @uid = (SELECT id FROM users WHERE email = 'shaikimran1027@gmail.com');
INSERT IGNORE INTO students (user_id, register_number, full_name, date_of_birth, gender, branch, mobile_number, alternate_number, address, approval_status, placement_status, placed_company) VALUES (@uid, '459CE23034', 'MOHAMMED IMRAN', '2006-09-12', 'Male', 'Civil', '9380702268', '9880445669', 'RUPANAGUDI ROAD near grand function hall', 'APPROVED', 'UNPLACED', '');
SET @sid = (SELECT id FROM students WHERE user_id = @uid);
INSERT IGNORE INTO academic_details (student_id, sslc_percentage, sslc_year, puc_percentage, puc_year, iti_percentage, iti_year, sem1, sem2, sem3, sem4, diploma_percentage, current_backlog_count, history_of_backlogs, preference) VALUES (@sid, 59.0, '2023', 0.0, '', 0.0, '', 68.1, 53.4, 66.3, 63.6, 62.85, 0, 'Yes', 'Higher Education');
INSERT IGNORE INTO users (email, password, role) VALUES ('Mohammedahmed632313@gmail.com', '459CE23035', 'STUDENT');
SET @uid = (SELECT id FROM users WHERE email = 'Mohammedahmed632313@gmail.com');
INSERT IGNORE INTO students (user_id, register_number, full_name, date_of_birth, gender, branch, mobile_number, alternate_number, address, approval_status, placement_status, placed_company) VALUES (@uid, '459CE23035', 'MOHAMMED PEER', '2005-12-26', 'Male', 'Civil', '7483136919', '8050387857', 'Sai datta nagar, mg road, ballari', 'APPROVED', 'UNPLACED', '');
SET @sid = (SELECT id FROM students WHERE user_id = @uid);
INSERT IGNORE INTO academic_details (student_id, sslc_percentage, sslc_year, puc_percentage, puc_year, iti_percentage, iti_year, sem1, sem2, sem3, sem4, diploma_percentage, current_backlog_count, history_of_backlogs, preference) VALUES (@sid, 58.4, '2023', 0.0, '', 0.0, '', 66.0, 61.5, 62.0, 64.2, 64.2, 0, 'No', 'Job');
INSERT IGNORE INTO users (email, password, role) VALUES ('sksshahid598@gmail.com', '459CE23036', 'STUDENT');
SET @uid = (SELECT id FROM users WHERE email = 'sksshahid598@gmail.com');
INSERT IGNORE INTO students (user_id, register_number, full_name, date_of_birth, gender, branch, mobile_number, alternate_number, address, approval_status, placement_status, placed_company) VALUES (@uid, '459CE23036', 'MOHAMMED SHAHID', '2007-01-05', 'Male', 'Civil', '7204527864', '9916178264', 'Abdul salam street', 'APPROVED', 'UNPLACED', '');
SET @sid = (SELECT id FROM students WHERE user_id = @uid);
INSERT IGNORE INTO academic_details (student_id, sslc_percentage, sslc_year, puc_percentage, puc_year, iti_percentage, iti_year, sem1, sem2, sem3, sem4, diploma_percentage, current_backlog_count, history_of_backlogs, preference) VALUES (@sid, 54.0, '2023', 0.0, '', 0.0, '', 63.6, 35.0, 67.4, 66.3, 58.07, 1, 'Yes', 'Job');
INSERT IGNORE INTO users (email, password, role) VALUES ('murarikm179@gmail.com', '459CE23039', 'STUDENT');
SET @uid = (SELECT id FROM users WHERE email = 'murarikm179@gmail.com');
INSERT IGNORE INTO students (user_id, register_number, full_name, date_of_birth, gender, branch, mobile_number, alternate_number, address, approval_status, placement_status, placed_company) VALUES (@uid, '459CE23039', 'MURARI K M', '2006-12-17', 'Male', 'Civil', '9353687017', '9353687017', 'Near ramala devi temple bandihatti cowl bazaar ballari', 'APPROVED', 'UNPLACED', '');
SET @sid = (SELECT id FROM students WHERE user_id = @uid);
INSERT IGNORE INTO academic_details (student_id, sslc_percentage, sslc_year, puc_percentage, puc_year, iti_percentage, iti_year, sem1, sem2, sem3, sem4, diploma_percentage, current_backlog_count, history_of_backlogs, preference) VALUES (@sid, 63.36, '2023', 0.0, '', 0.0, '', 74.7, 68.0, 75.6, 77.9, 74.05, 0, 'Yes', 'Job');
INSERT IGNORE INTO users (email, password, role) VALUES ('sn755465@gmail.com', '459CE23041', 'STUDENT');
SET @uid = (SELECT id FROM users WHERE email = 'sn755465@gmail.com');
INSERT IGNORE INTO students (user_id, register_number, full_name, date_of_birth, gender, branch, mobile_number, alternate_number, address, approval_status, placement_status, placed_company) VALUES (@uid, '459CE23041', 'N SHIVARAJ', '2006-11-15', 'Male', 'Civil', '9482206149', '8951783969', 'Sudha cross, behind nandi Honda showroom, LLC colony, Ballari.', 'APPROVED', 'UNPLACED', '');
SET @sid = (SELECT id FROM students WHERE user_id = @uid);
INSERT IGNORE INTO academic_details (student_id, sslc_percentage, sslc_year, puc_percentage, puc_year, iti_percentage, iti_year, sem1, sem2, sem3, sem4, diploma_percentage, current_backlog_count, history_of_backlogs, preference) VALUES (@sid, 87.68, '2022-23', 0.0, '', 0.0, '', 88.1, 92.5, 92.5, 92.5, 91.4, 0, 'No', 'Job');
INSERT IGNORE INTO users (email, password, role) VALUES ('Kataginagaraj48@gmail.com', '459CE23042', 'STUDENT');
SET @uid = (SELECT id FROM users WHERE email = 'Kataginagaraj48@gmail.com');
INSERT IGNORE INTO students (user_id, register_number, full_name, date_of_birth, gender, branch, mobile_number, alternate_number, address, approval_status, placement_status, placed_company) VALUES (@uid, '459CE23042', 'NAGARAJ', '2007-08-21', 'Male', 'Civil', '6360027213', '9741949783', '2nd ward BENNUR OOLENUR KOPPAL DIST', 'APPROVED', 'UNPLACED', '');
SET @sid = (SELECT id FROM students WHERE user_id = @uid);
INSERT IGNORE INTO academic_details (student_id, sslc_percentage, sslc_year, puc_percentage, puc_year, iti_percentage, iti_year, sem1, sem2, sem3, sem4, diploma_percentage, current_backlog_count, history_of_backlogs, preference) VALUES (@sid, 71.2, '2023', 0.0, '', 0.0, '', 43.6, 52.5, 59.4, 59.4, 53.72, 1, 'Yes', 'Job');
INSERT IGNORE INTO users (email, password, role) VALUES ('cnandish75@gmail.com', '459CE23043', 'STUDENT');
SET @uid = (SELECT id FROM users WHERE email = 'cnandish75@gmail.com');
INSERT IGNORE INTO students (user_id, register_number, full_name, date_of_birth, gender, branch, mobile_number, alternate_number, address, approval_status, placement_status, placed_company) VALUES (@uid, '459CE23043', 'NANDISHA C', '2005-11-11', 'Male', 'Civil', '7892917722', '9880614092', '3/152 JANATHA 1ST 2ND WARD Y KAGGAL BALLARI', 'APPROVED', 'UNPLACED', '');
SET @sid = (SELECT id FROM students WHERE user_id = @uid);
INSERT IGNORE INTO academic_details (student_id, sslc_percentage, sslc_year, puc_percentage, puc_year, iti_percentage, iti_year, sem1, sem2, sem3, sem4, diploma_percentage, current_backlog_count, history_of_backlogs, preference) VALUES (@sid, 418.0, '2023', 0.0, '', 0.0, '', 50.3, 48.9, 64.8, 64.0, 57.0, 1, 'Yes', 'Job');
INSERT IGNORE INTO users (email, password, role) VALUES ('mrjunnubrand@gmail.com', '459CE23047', 'STUDENT');
SET @uid = (SELECT id FROM users WHERE email = 'mrjunnubrand@gmail.com');
INSERT IGNORE INTO students (user_id, register_number, full_name, date_of_birth, gender, branch, mobile_number, alternate_number, address, approval_status, placement_status, placed_company) VALUES (@uid, '459CE23047', 'S MD JUNAID', '2005-11-12', 'Male', 'Civil', '8217474424', '8217674424', 'Nabi colony Ballari', 'APPROVED', 'UNPLACED', '');
SET @sid = (SELECT id FROM students WHERE user_id = @uid);
INSERT IGNORE INTO academic_details (student_id, sslc_percentage, sslc_year, puc_percentage, puc_year, iti_percentage, iti_year, sem1, sem2, sem3, sem4, diploma_percentage, current_backlog_count, history_of_backlogs, preference) VALUES (@sid, 70.0, '2023', 0.0, '', 0.0, '', 78.0, 75.0, 68.0, 73.0, 72.05, 0, 'No', 'Job');
INSERT IGNORE INTO users (email, password, role) VALUES ('varun5kumar001@gmail.com', '459CE23049', 'STUDENT');
SET @uid = (SELECT id FROM users WHERE email = 'varun5kumar001@gmail.com');
INSERT IGNORE INTO students (user_id, register_number, full_name, date_of_birth, gender, branch, mobile_number, alternate_number, address, approval_status, placement_status, placed_company) VALUES (@uid, '459CE23049', 'SHIVA SHANKAR', '2007-05-21', 'Male', 'Civil', '9972361801', '7899439875', 'ESHWARAMMA TEMPLE  BEHIND BASAVANAKUNTA BALLARI', 'APPROVED', 'UNPLACED', '');
SET @sid = (SELECT id FROM students WHERE user_id = @uid);
INSERT IGNORE INTO academic_details (student_id, sslc_percentage, sslc_year, puc_percentage, puc_year, iti_percentage, iti_year, sem1, sem2, sem3, sem4, diploma_percentage, current_backlog_count, history_of_backlogs, preference) VALUES (@sid, 61.6, '2023', 0.0, '', 0.0, '', 68.1, 65.2, 74.8, 77.9, 71.5, 0, 'Yes', 'Job');
INSERT IGNORE INTO users (email, password, role) VALUES ('Siddalinga8618@gmail.com', '459CE23051', 'STUDENT');
SET @uid = (SELECT id FROM users WHERE email = 'Siddalinga8618@gmail.com');
INSERT IGNORE INTO students (user_id, register_number, full_name, date_of_birth, gender, branch, mobile_number, alternate_number, address, approval_status, placement_status, placed_company) VALUES (@uid, '459CE23051', 'SIDDALINGA G', '2007-06-01', 'Male', 'Civil', '8618975907', '9740264279', 's/o HULITEPPA, #33,GOUDRA ONI, DAMMUR KAGGALU, BALLARI', 'APPROVED', 'UNPLACED', '');
SET @sid = (SELECT id FROM students WHERE user_id = @uid);
INSERT IGNORE INTO academic_details (student_id, sslc_percentage, sslc_year, puc_percentage, puc_year, iti_percentage, iti_year, sem1, sem2, sem3, sem4, diploma_percentage, current_backlog_count, history_of_backlogs, preference) VALUES (@sid, 74.0, '2023', 0.0, '', 0.0, '', 72.5, 72.5, 81.7, 81.0, 76.92, 0, 'Yes', 'Job');
INSERT IGNORE INTO users (email, password, role) VALUES ('syedfarid789@gmail.com', '459CE23052', 'STUDENT');
SET @uid = (SELECT id FROM users WHERE email = 'syedfarid789@gmail.com');
INSERT IGNORE INTO students (user_id, register_number, full_name, date_of_birth, gender, branch, mobile_number, alternate_number, address, approval_status, placement_status, placed_company) VALUES (@uid, '459CE23052', 'SYED KHWAJA FARIDUDDIN', '2005-03-06', 'Male', 'Civil', '6361352845', '7975746607', '16/6 AULIYA MANZIL MOHAMMAD YUSUF SAB STREET BANDIMOTE BALLARI', 'APPROVED', 'UNPLACED', '');
SET @sid = (SELECT id FROM students WHERE user_id = @uid);
INSERT IGNORE INTO academic_details (student_id, sslc_percentage, sslc_year, puc_percentage, puc_year, iti_percentage, iti_year, sem1, sem2, sem3, sem4, diploma_percentage, current_backlog_count, history_of_backlogs, preference) VALUES (@sid, 58.0, '2021', 0.0, '', 0.0, '', 34.7, 19.8, 50.2, 47.9, 38.15, 3, 'Yes', 'Job');
INSERT IGNORE INTO users (email, password, role) VALUES ('syedtabraiz75@gmail.com', '459CE23053', 'STUDENT');
SET @uid = (SELECT id FROM users WHERE email = 'syedtabraiz75@gmail.com');
INSERT IGNORE INTO students (user_id, register_number, full_name, date_of_birth, gender, branch, mobile_number, alternate_number, address, approval_status, placement_status, placed_company) VALUES (@uid, '459CE23053', 'SYED TABEAIZ KHADRI', '2005-01-23', 'Male', 'Civil', '8310480098', '8310480098', 'Ghughurahatti jannatul ferdous masjid ballari', 'APPROVED', 'UNPLACED', '');
SET @sid = (SELECT id FROM students WHERE user_id = @uid);
INSERT IGNORE INTO academic_details (student_id, sslc_percentage, sslc_year, puc_percentage, puc_year, iti_percentage, iti_year, sem1, sem2, sem3, sem4, diploma_percentage, current_backlog_count, history_of_backlogs, preference) VALUES (@sid, 57.0, 'PASS', 0.0, '', 0.0, '', 0.0, 0.0, 0.0, 0.0, 57.0, 2, 'Yes', 'Job');
INSERT IGNORE INTO users (email, password, role) VALUES ('kthippeswamy649@gmail.com', '459CE23055', 'STUDENT');
SET @uid = (SELECT id FROM users WHERE email = 'kthippeswamy649@gmail.com');
INSERT IGNORE INTO students (user_id, register_number, full_name, date_of_birth, gender, branch, mobile_number, alternate_number, address, approval_status, placement_status, placed_company) VALUES (@uid, '459CE23055', 'THIPPESWAMY K', '2005-08-03', 'Male', 'Civil', '7899346801', '7899346801', 'Ward no 3 shankar gudda linga temple toranagallu', 'APPROVED', 'UNPLACED', '');
SET @sid = (SELECT id FROM students WHERE user_id = @uid);
INSERT IGNORE INTO academic_details (student_id, sslc_percentage, sslc_year, puc_percentage, puc_year, iti_percentage, iti_year, sem1, sem2, sem3, sem4, diploma_percentage, current_backlog_count, history_of_backlogs, preference) VALUES (@sid, 85.12, '2021', 0.0, '', 0.0, '', 51.4, 36.1, 51.0, 53.3, 47.75, 2, 'Yes', 'Job');
INSERT IGNORE INTO users (email, password, role) VALUES ('udaymuday814@gmail.com', '459CE23056', 'STUDENT');
SET @uid = (SELECT id FROM users WHERE email = 'udaymuday814@gmail.com');
INSERT IGNORE INTO students (user_id, register_number, full_name, date_of_birth, gender, branch, mobile_number, alternate_number, address, approval_status, placement_status, placed_company) VALUES (@uid, '459CE23056', 'UDAYA SHANKARA', '2006-07-04', 'Male', 'Civil', '7259197581', '8660527219', 'PUNEETH RAJ KUMAR COLONY 3RD WARD KUDATHINI', 'APPROVED', 'UNPLACED', '');
SET @sid = (SELECT id FROM students WHERE user_id = @uid);
INSERT IGNORE INTO academic_details (student_id, sslc_percentage, sslc_year, puc_percentage, puc_year, iti_percentage, iti_year, sem1, sem2, sem3, sem4, diploma_percentage, current_backlog_count, history_of_backlogs, preference) VALUES (@sid, 77.12, '2023', 0.0, '', 0.0, '', 70.3, 55.2, 64.0, 55.6, 61.25, 0, 'No', 'Job');
INSERT IGNORE INTO users (email, password, role) VALUES ('jwalathi06@gmail.com', '459CE23057', 'STUDENT');
SET @uid = (SELECT id FROM users WHERE email = 'jwalathi06@gmail.com');
INSERT IGNORE INTO students (user_id, register_number, full_name, date_of_birth, gender, branch, mobile_number, alternate_number, address, approval_status, placement_status, placed_company) VALUES (@uid, '459CE23057', 'V JWALATHI JYOTHIRMAI', '2007-06-06', 'Female', 'Civil', '9743390937', '7204052798', 'H.No-EWS33,ward no -39, KHB colony, Netaji Nagar, Ballari', 'APPROVED', 'UNPLACED', '');
SET @sid = (SELECT id FROM students WHERE user_id = @uid);
INSERT IGNORE INTO academic_details (student_id, sslc_percentage, sslc_year, puc_percentage, puc_year, iti_percentage, iti_year, sem1, sem2, sem3, sem4, diploma_percentage, current_backlog_count, history_of_backlogs, preference) VALUES (@sid, 85.92, '2023', 0.0, '', 0.0, '', 90.3, 91.6, 91.7, 92.5, 91.53, 0, 'No', 'Higher Education');
INSERT IGNORE INTO users (email, password, role) VALUES ('am6001762@gmail.com', '459CE23059', 'STUDENT');
SET @uid = (SELECT id FROM users WHERE email = 'am6001762@gmail.com');
INSERT IGNORE INTO students (user_id, register_number, full_name, date_of_birth, gender, branch, mobile_number, alternate_number, address, approval_status, placement_status, placed_company) VALUES (@uid, '459CE23059', 'VINAYA KUMAR M', '2007-03-26', 'Male', 'Civil', '8150002723', '9448977277', 'NEAR DYVAMMA TEMPLE VADDU', 'APPROVED', 'UNPLACED', '');
SET @sid = (SELECT id FROM students WHERE user_id = @uid);
INSERT IGNORE INTO academic_details (student_id, sslc_percentage, sslc_year, puc_percentage, puc_year, iti_percentage, iti_year, sem1, sem2, sem3, sem4, diploma_percentage, current_backlog_count, history_of_backlogs, preference) VALUES (@sid, 77.44, '2023', 0.0, '', 0.0, '', 71.4, 59.8, 65.8, 65.8, 65.7, 0, 'Yes', 'Job');
INSERT IGNORE INTO users (email, password, role) VALUES ('vishwas.klm98@gmail.com', '459CE23060', 'STUDENT');
SET @uid = (SELECT id FROM users WHERE email = 'vishwas.klm98@gmail.com');
INSERT IGNORE INTO students (user_id, register_number, full_name, date_of_birth, gender, branch, mobile_number, alternate_number, address, approval_status, placement_status, placed_company) VALUES (@uid, '459CE23060', 'VISHWANATHA', '2004-03-27', 'Male', 'Civil', '6363507098', '7975843043', 'Near sajje hola kalamangi/Raichur', 'APPROVED', 'UNPLACED', '');
SET @sid = (SELECT id FROM students WHERE user_id = @uid);
INSERT IGNORE INTO academic_details (student_id, sslc_percentage, sslc_year, puc_percentage, puc_year, iti_percentage, iti_year, sem1, sem2, sem3, sem4, diploma_percentage, current_backlog_count, history_of_backlogs, preference) VALUES (@sid, 69.92, '2019', 0.0, '', 0.0, '', 51.4, 45.2, 54.8, 61.7, 53.27, 2, 'Yes', 'Job');
INSERT IGNORE INTO users (email, password, role) VALUES ('yaterajendra0@gmail.com', '459CE23061', 'STUDENT');
SET @uid = (SELECT id FROM users WHERE email = 'yaterajendra0@gmail.com');
INSERT IGNORE INTO students (user_id, register_number, full_name, date_of_birth, gender, branch, mobile_number, alternate_number, address, approval_status, placement_status, placed_company) VALUES (@uid, '459CE23061', 'YATE RAJENDRA', '2007-01-01', 'Male', 'Civil', '8867438897', '8867438897', '1-8 kogilathota village  Holagunda mandal alur Thaluk kurnool', 'APPROVED', 'UNPLACED', '');
SET @sid = (SELECT id FROM students WHERE user_id = @uid);
INSERT IGNORE INTO academic_details (student_id, sslc_percentage, sslc_year, puc_percentage, puc_year, iti_percentage, iti_year, sem1, sem2, sem3, sem4, diploma_percentage, current_backlog_count, history_of_backlogs, preference) VALUES (@sid, 51.33, '22-23', 0.0, '', 0.0, '', 84.7, 88.9, 92.5, 92.5, 89.65, 0, 'No', 'Job');
INSERT IGNORE INTO users (email, password, role) VALUES ('royalconstructions55@gmail.com', '459CE24301', 'STUDENT');
SET @uid = (SELECT id FROM users WHERE email = 'royalconstructions55@gmail.com');
INSERT IGNORE INTO students (user_id, register_number, full_name, date_of_birth, gender, branch, mobile_number, alternate_number, address, approval_status, placement_status, placed_company) VALUES (@uid, '459CE24301', 'SYED IBRAHIM', '1989-04-06', 'Male', 'Civil', '9738950555', '9113242245', 'Ward no 33, door no 180, devi nagar Ballari', 'APPROVED', 'UNPLACED', '');
SET @sid = (SELECT id FROM students WHERE user_id = @uid);
INSERT IGNORE INTO academic_details (student_id, sslc_percentage, sslc_year, puc_percentage, puc_year, iti_percentage, iti_year, sem1, sem2, sem3, sem4, diploma_percentage, current_backlog_count, history_of_backlogs, preference) VALUES (@sid, 53.9, '2005', 0.0, '', 81.0, '2018', 0.0, 0.0, 71.0, 71.0, 71.0, 0, 'Yes', 'Higher Education');
INSERT IGNORE INTO users (email, password, role) VALUES ('syedanassyedanas168@gmail.com', '459CE24702', 'STUDENT');
SET @uid = (SELECT id FROM users WHERE email = 'syedanassyedanas168@gmail.com');
INSERT IGNORE INTO students (user_id, register_number, full_name, date_of_birth, gender, branch, mobile_number, alternate_number, address, approval_status, placement_status, placed_company) VALUES (@uid, '459CE24702', 'SYED MOHAMMED ANAS', '2005-07-09', 'Male', 'Civil', '9448481494', '6360926474', 'DEVAINAGAR BELLARI', 'APPROVED', 'PLACED', 'Yazaki India PvT Ltd');
SET @sid = (SELECT id FROM students WHERE user_id = @uid);
INSERT IGNORE INTO academic_details (student_id, sslc_percentage, sslc_year, puc_percentage, puc_year, iti_percentage, iti_year, sem1, sem2, sem3, sem4, diploma_percentage, current_backlog_count, history_of_backlogs, preference) VALUES (@sid, 80.64, '2022', 63.33, '2024', 0.0, '', 0.0, 0.0, 81.76, 75.6, 75.6, 0, 'No', 'Higher Education');
SET FOREIGN_KEY_CHECKS=1;
